docs_dir: docs
site_name: Robotický tábor 2026
site_url: https://2026.robotickytabor.cz/
site_description: >-
  Robotický tábor 2026

repo_name: RoboticsBrno/RoboCamp-2026
repo_url: https://github.com/RoboticsBrno/RoboCamp-2026
# edit_uri: blob/main/docs/

dev_addr: "127.0.0.1:8000"
copyright: Copyright © RoboticsBrno
use_directory_urls: True

theme:
  name: material
  language: cs
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.annotate
  custom_dir: overrides

  icon:
    repo: fontawesome/brands/github

  palette:
    - scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Přepnout na světý režim
    - scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Přepnout na tmavý režim

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - meta
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      url_download: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "¤"
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - open-in-new-tab
  - glightbox:
      auto_caption: true
  - resize-images:
      source-dir: assets-large
      target-dir: assets
      enable_cache: True
      size: [1000, 800]
      extensions: [".jpg", ".jpeg", ".png", ".gif"]
  # - typedoc:
  #     source: "./docs/elks/lekce1/example1/@types/*.d.ts"
  #     output_dir: "jaculusApi"
  #     tsconfig: "./docs/elks/lekce1/example1/tsconfig.json"
  #     options: "typedoc.json"
  #     name: "Jaculus API documentation"

  - zip_folders:
      folders:
        - lekce/baseExample
        - lekce/lekce4-5/example45
        - moduly/dpad/dpad-example
        - moduly/enkoder/enkoder-example
        - moduly/gyro/gyro-example
        - moduly/ir/ir-example
        - moduly/joystick/joystick-example
        - moduly/fotorezistor/fotorezistor-example
        - moduly/piezo/piezo-example
        - moduly/rfid/rfid-example
        - moduly/rtc/rtc-example
        - moduly/teplota/teplota-example
        - moduly/dpad/dpad-example
      formats:
        - zip
        - tar.gz
      debug: true

  - auto-refresh-build-pages:
      update_message: "Návod byl aktualizován, chcete načíst novou verzi?"
      yes_button_text: "Ano"
      no_button_text: "Ne"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RoboticsBrno
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/RobotikaBrno
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/robotarna.helceletka
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@robotikabrno-robotarnaasps2392
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/robotarna.helceletka

extra_css:
  - assets/style.css

nav:
  - Domů:
      - index.md
  - Stavba Robodecku:
      - robodeck/index.md
      - robodeck/kroky/01-pajeni.md
      - robodeck/kroky/02-ramecek.md
      - robodeck/kroky/03-spojeni.md
      - robodeck/kroky/04-dokonceni.md
  - Programovací lekce:
      - lekce/index.md
      - lekce/faq/index.md
      - lekce/lekce0/index.md
      - lekce/lekce1/index.md
      - lekce/lekce2/index.md
      - lekce/lekce2-1/index.md
      - lekce/lekce3/index.md
      - lekce/lekce4/index.md
      - lekce/lekce4-5/index.md
      - lekce/lekce5/index.md
      - lekce/lekce6/index.md
      - lekce/lekce7/index.md
      #- lekce/lekce8/index.md
      #- lekce/lekce9/index.md
      - lekce/scene-builder/index.md
      - lekce/programKoncepty/index.md
  - Rozšířující moduly:
      - moduly/index.md
      - moduly/dpad/index.md
      - moduly/gyro/index.md
      - moduly/ir/index.md
      - moduly/joystick/index.md
      - moduly/fotorezistor/index.md
      - moduly/piezo/index.md
      - moduly/enkoder/index.md
      - moduly/rfid/index.md
      - moduly/rtc/index.md
      - moduly/teplota/index.md
  - Programovací výzvy:
      - challenge/index.md
      - challenge/snake.md
      - challenge/tetris.md
      - challenge/fire.md
      - challenge/game_of_life.md
      - challenge/asteroids.md
